name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag nodeapp:$(date +%s)
    - name: login to docker hub
      run: echo ${{secrets.DOCKER_ACCESS}} | docker login -u ${{secrets.DOCKER_USER}} --password-stdin 
    - name: push to docker 
      run: docker push nodeapp:$(date +%s)
